### ISSUE TITLE
jterminal-1.0.2.3-loomcom missing from maven central

### ISSUE THREAD

**Issue by ccureau** [sethm/symon#22]
Attempting to compile today gives the following issue:

`[ERROR] Failed to execute goal on project symon: Could not resolve dependencies for project com.loomcom.symon:symon:jar:1.3.0-SNAPSHOT: Could not find artifact com.grahamedgecombe.jterminal:jterminal:jar:1.0.2.3-loomcom in nexus-cid (http://10.227.80.46/repository/Mvn-central/) -> [Help 1]`

Attempting to use version 1.0.1 fails with missing methods.

**Proposed fix** - fork jterminal, add our customization, and build with symon

**Comment by ccureau** [comment]
@sethm Do you have the modifications for the jterminal source?

**Comment by sethm** [comment]
Ouch, this was a result of my changing hosts recently, and not enabling Indexes in Apache. In the short term, it should be fixed now if you try to build again. But I think integrating the source into the symon code base is probably the right thing to do.

Modifications are in my fork, here, from long long ago: https://github.com/sethm/jterminal

**Comment by ccureau** [comment]
Thanks for the repo!  Its still not available in maven central, but after
compiling and installing locally all is good with the world.

**Comment by ccureau** [comment]
I've added the source for jterminal (including the JTerminal.java from a decompile of jterminal-1.0.2.3-loomom.jar) and tested.
